/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.statify;

/**
 *
 * @author mwewior
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents                       
    private void initComponents() {

        planeRoot = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        additionalPanel = new javax.swing.JPanel();
        typeActionPanel = new javax.swing.JPanel();
        genreButon = new javax.swing.JButton();
        artistButton1 = new javax.swing.JButton();
        logoPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        centrePanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        timePeriodPanel = new javax.swing.JPanel();
        weeks4Button = new javax.swing.JButton();
        months6Button = new javax.swing.JButton();
        allTimeHistoryButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        planeRoot.setMaximumSize(new java.awt.Dimension(1980, 1080));
        planeRoot.setPreferredSize(new java.awt.Dimension(960, 540));
        planeRoot.setLayout(new java.awt.BorderLayout());

        sidePanel.setBackground(new java.awt.Color(44, 51, 51));
        sidePanel.setPreferredSize(new java.awt.Dimension(210, 540));
        sidePanel.setLayout(new java.awt.BorderLayout());

        additionalPanel.setBackground(new java.awt.Color(44, 51, 51));
        additionalPanel.setPreferredSize(new java.awt.Dimension(210, 70));

        javax.swing.GroupLayout additionalPanelLayout = new javax.swing.GroupLayout(additionalPanel);
        additionalPanel.setLayout(additionalPanelLayout);
        additionalPanelLayout.setHorizontalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        additionalPanelLayout.setVerticalGroup(
            additionalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        sidePanel.add(additionalPanel, java.awt.BorderLayout.SOUTH);

        typeActionPanel.setBackground(new java.awt.Color(44, 51, 51));
        typeActionPanel.setPreferredSize(new java.awt.Dimension(210, 420));

        genreButon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-music-record-32.png"))); // NOI18N
        genreButon.setText("gatunek");
        genreButon.setBorder(null);
        genreButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreButonActionPerformed(evt);
            }
        });

        artistButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-musician-male-32.png"))); // NOI18N
        artistButton1.setText("artysta");
        artistButton1.setBorder(null);
        artistButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typeActionPanelLayout = new javax.swing.GroupLayout(typeActionPanel);
        typeActionPanel.setLayout(typeActionPanelLayout);
        typeActionPanelLayout.setHorizontalGroup(
            typeActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeActionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typeActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(typeActionPanelLayout.createSequentialGroup()
                        .addComponent(artistButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typeActionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(genreButon, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        typeActionPanelLayout.setVerticalGroup(
            typeActionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeActionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(artistButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genreButon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        sidePanel.add(typeActionPanel, java.awt.BorderLayout.CENTER);

        logoPanel.setBackground(new java.awt.Color(44, 51, 51));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        sidePanel.add(logoPanel, java.awt.BorderLayout.NORTH);

        planeRoot.add(sidePanel, java.awt.BorderLayout.WEST);

        mainPanel.setBackground(new java.awt.Color(46, 79, 79));
        mainPanel.setPreferredSize(new java.awt.Dimension(750, 540));
        mainPanel.setLayout(new java.awt.BorderLayout());

        centrePanel.setLayout(new java.awt.BorderLayout());

        actionPanel.setBackground(new java.awt.Color(46, 79, 79));

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        centrePanel.add(actionPanel, java.awt.BorderLayout.CENTER);

        timePeriodPanel.setBackground(new java.awt.Color(46, 79, 79));
        timePeriodPanel.setPreferredSize(new java.awt.Dimension(20, 120));
        timePeriodPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 97, 48));

        weeks4Button.setText("4 tygodnie");
        weeks4Button.setPreferredSize(new java.awt.Dimension(108, 54));
        weeks4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeks4ButtonActionPerformed(evt);
            }
        });
        timePeriodPanel.add(weeks4Button);

        months6Button.setText("6 miesięcy");
        months6Button.setPreferredSize(new java.awt.Dimension(108, 54));
        months6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                months6ButtonActionPerformed(evt);
            }
        });
        timePeriodPanel.add(months6Button);

        allTimeHistoryButton.setText("cała historia");
        allTimeHistoryButton.setPreferredSize(new java.awt.Dimension(108, 54));
        timePeriodPanel.add(allTimeHistoryButton);

        centrePanel.add(timePeriodPanel, java.awt.BorderLayout.NORTH);

        mainPanel.add(centrePanel, java.awt.BorderLayout.CENTER);

        planeRoot.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(planeRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void genreButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreButonActionPerformed


    private void artistButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistButton1ActionPerformed


    private void months6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_months6ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_months6ButtonActionPerformed

    private void weeks4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeks4ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeks4ButtonActionPerformed


    /**
     * @param args the command line arguments
     */

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel additionalPanel;
    private javax.swing.JButton allTimeHistoryButton;
    private javax.swing.JButton artistButton1;
    private javax.swing.JPanel centrePanel;
    private javax.swing.JButton genreButon;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton months6Button;
    private javax.swing.JPanel planeRoot;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel timePeriodPanel;
    private javax.swing.JPanel typeActionPanel;
    private javax.swing.JButton weeks4Button;
    // End of variables declaration                   
}
